version: '3.8'

services:
  askme-chat-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.askme-chat.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.askme-chat.entrypoints=web"
      - "traefik.http.routers.askme-chat.tls.certresolver=letsencrypt"
